apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Chart.Name }}-config
  labels:
    app: {{ .Chart.Name }}
data:
  S3_BUCKET: {{ .Values.env.S3_BUCKET | quote }}
  AWS_REGION: {{ .Values.env.AWS_REGION | quote }}
  ATHENA_DATABASE: {{ .Values.env.ATHENA_DATABASE | quote }}
  ATHENA_WORKGROUP: {{ .Values.env.ATHENA_WORKGROUP | quote }}
